alias = {
    'Keenan': {'Trevor Keenan', 'Trevor F. Keenan'},
    'Li': {'Yue Li'},
    'Wang': {'Yaoping Wang'},
    'Mao': {'J. Mao', 'Jiafu Mao'},
    'Shi': {'Xiaoying Shi', 'Xioaying Shi'},
    'Randerson': {'J. T. Randerson', 'J. Randerson', 'James T. Randerson', 'James Randerson'},
    'Xu': {'Min Xu'},
    'Hoffman': {'Forrest M. Hoffman', 'Forrest Hoffman', 'F. Hoffman', 'F. M. Hoffman'},
    'Tang': {'Jinyun Tang', 'J. Y. Tang'},
    'Riley': {'W. Riley', 'W. J. Riley', 'William J. Riley', 'William Riley'},
    'Koven': {'Charles D. Koven', 'C. D. Koven', 'Charlie Koven', 'C. Koven', 'Charles Koven'},
    'Lawrence': {'Deborah Lawrence', 'David Lawrence', 'Peter J. Lawrence', 'David M. Lawrence', 'D. Lawrence', 'D. M. Lawrence', 'Corey R. Lawrence', 'Peter Lawrence'},
    'Mu': {'Mingquan Mu'},
    'Moore': {' J.Keith Moore', 'J. K. Moore', 'J. Keith Moore', 'J. C. Moore', 'David J. P. Moore', 'John C. Moore'},
    'Mishra': {'Umakant Mishra', 'U. Mishra'},
    'Keppel-Aleks': {'Gretchen Keppel-Aleks'},
    'Zhu': {'Zaichun Zhu', 'Q. Zhu', 'Qing Zhu', 'X. Zhu', 'Peng Zhu', 'Qiuan Zhu'},
    'Kumar': {'Sujay V. Kumar', 'Jitendra Kumar', 'Sandeep Kumar', 'Sanjiv Kumar'},
    'Collier': {'Nathan Collier'},
    'Mekonnen': {'Zelalem A. Mekonnen'},
    'Fu': {'Joshua S. Fu', 'Weiwei Fu', 'Li Fu', 'Wenting Fu'},
    'Chang': {'Kuang-Yu Chang', 'Rachel Y.-W. Chang', 'P. Chang'},
    'Negron-Juarez': {'Robinson I. Negron-Juarez', 'R. Negron-Juarez', 'Robinson Negron-Juarez'}
}
