alias = {
    'Chen': {'Chi Chen'},
    'Keenan': {'Trevor Keenan', 'Trevor F. Keenan'},
    'Wang': {'Y. Wang', 'Yaoping Wang'},
    'Mao': {'Jiafu Mao', 'J. Mao'},
    'Randerson': {'James T. Randerson', 'J. Randerson', 'J. T. Randerson', 'James Randerson'},
    'Hoffman': {'Forrest M. Hoffman', 'F. M. Hoffman', 'Forrest Hoffman', 'F. Hoffman'},
    'Tang': {'Jinyun Tang', 'J. Y. Tang'},
    'Riley': {'William Riley', 'W. J. Riley', 'W. Riley', 'William J. Riley'},
    'Koven': {'C. Koven', 'Charlie Koven', 'Charles D. Koven', 'C. D. Koven', 'Charles Koven'},
    'Lawrence': {'D. M. Lawrence', 'David M. Lawrence', 'David Lawrence', 'D. Lawrence'},
    'Liu': {'Yi Y. Liu'},
    'Mu': {'Mingquan Mu'},
    'Moore': {'J. Keith Moore', 'J. K. Moore', ' J.Keith Moore'},
    'Mishra': {'Umakant Mishra', 'U. Mishra'},
    'Keppel-Aleks': {'Gretchen Keppel-Aleks'},
    'Zhu': {'Qing Zhu', 'Q. Zhu'},
    'Kumar': {'Jitendra Kumar'},
    'Collier': {'Nathan Collier'},
    'Mekonnen': {'Zelalem A. Mekonnen'},
    'Sharma': {'Bharat Sharma'},
    'Fu': {'Weiwei Fu'},
    'Chang': {'Kuang-Yu Chang'},
    'Negron-Juarez': {'R. Negron-Juarez', 'Robinson I. Negron-Juarez', 'Robinson Negron-Juarez'},
    'M. Xu': {'Min Xu'},
    'L. Xu': {'Li Xu'},
    'Li': {'Yue Li'},    
    'X. Shi': {'Xioaying Shi', 'Xiaoying Shi'},
    'Z. Shi': {'Zheng Shi'},
}
aff = {
    'Chen': 'LBNL',
    'Keenan': 'LBNL',
    'Wang': 'ORNL',
    'Mao': 'ORNL', 
    'Randerson': 'UCI',
    'Hoffman': 'ORNL', 
    'Tang': 'LBNL', 
    'Riley': 'LBNL', 
    'Koven': 'LBNL', 
    'Lawrence': 'NCAR', 
    'Liu': 'UCI',
    'Mu': 'UCI', 
    'Moore': 'UCI', 
    'Mishra': 'SNL', 
    'Keppel-Aleks': 'UM',
    'Zhu': 'LBNL',
    'Kumar': 'ORNL',
    'Collier': 'ORNL',
    'Mekonnen': 'LBNL',
    'Sharma': 'ORNL',
    'Fu': 'UCI',
    'Chang': 'LBNL',
    'Negron-Juarez': 'LBNL',
    'M. Xu': 'ORNL',
    'L. Xu': 'UCI',
    'Li': 'UCI', 
    'X. Shi': 'ORNL', 
    'Z. Shi': 'UCI', 
}
